spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: product
server:
  port: 10001
  servlet:
    context-path: /product
mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: mapper/*.xml
