spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: order
  redis:
    port: 6379
    host: 192.168.23.9
    database: 0
server:
  port: 10003
mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: mapper/*.xml
